# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a03603380ecd8bed88a2eadf74d70eb78bd564dca75df73b2a7c16e7e523fc5cfa878e3563d0df662aef771f9a19a14c4997167fb383f5c4d05910a42f31181

test:
  secret_key_base: 7609ed77573d7f83c440b869f184c6bc7c24e1c6e4636717e778ffe3c95034cb15ae27436671ea1f5698f1a35d1b06dfc23445daceeb65992972900bec6f9b08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
